import type { DatabaseSync } from "node:sqlite";
import type { CatalogItem, ProposedItem } from "./types.js";

export class CommerceTruthEngine {
  private db: DatabaseSync;

  constructor(db: DatabaseSync) {
    this.db = db;
  }

  /**
   * Seed standard merchant catalog items if empty.
   */
  public seedDefaultCatalog(): void {
    const row = this.db.prepare("SELECT COUNT(*) as count FROM catalog_items").get() as { count: number | bigint };
    const count = Number(row.count);
    if (count === 0) {
      const insert = this.db.prepare(`
        INSERT INTO catalog_items (sku, name, category, unit_price, tax_rate_bps, available_stock, is_active)
        VALUES (?, ?, ?, ?, ?, ?, ?)
      `);

      const defaultItems: CatalogItem[] = [
        {
          sku: "SKU-KEYBOARD-RGB",
          name: "Wireless Mechanical Keyboard (RGB)",
          category: "electronics",
          unit_price: 350000, // INR 3,500.00
          tax_rate_bps: 1800, // 18% GST (INR 630.00 -> Total INR 4,130.00)
          available_stock: 5,
          is_active: true,
        },
        {
          sku: "SKU-MOUSE-PRO",
          name: "Ergonomic Optical Gaming Mouse",
          category: "electronics",
          unit_price: 180000, // INR 1,800.00
          tax_rate_bps: 1800, // 18% GST (INR 324.00 -> Total INR 2,124.00)
          available_stock: 12,
          is_active: true,
        },
        {
          sku: "SKU-CHAIR-ERGO",
          name: "Executive Ergonomic Mesh Chair",
          category: "furniture",
          unit_price: 1200000, // INR 12,000.00
          tax_rate_bps: 1800, // 18% GST (INR 2,160.00 -> Total INR 14,160.00)
          available_stock: 3,
          is_active: true,
        },
      ];

      for (const item of defaultItems) {
        insert.run(
          item.sku,
          item.name,
          item.category,
          item.unit_price,
          item.tax_rate_bps,
          item.available_stock,
          item.is_active ? 1 : 0
        );
      }
    }
  }

  /**
   * Resolves proposed items from LLM against canonical database truth.
   * Completely ignores any price/tax claim generated by the LLM.
   */
  public resolveTruth(proposedItems: ProposedItem[]): {
    isValid: boolean;
    error?: string;
    resolvedItems: Array<{
      item: CatalogItem;
      quantity: number;
      subtotal: number;
      tax: number;
      total: number;
    }>;
    totalAmount: number; // in paise
    totalTax: number;
    categories: string[];
  } {
    const resolved = [];
    let grandTotal = 0;
    let grandTax = 0;
    const categoriesSet = new Set<string>();

    const getItemStmt = this.db.prepare("SELECT * FROM catalog_items WHERE sku = ? AND is_active = 1");

    for (const proposed of proposedItems) {
      const row = getItemStmt.get(proposed.sku) as unknown as CatalogItem | undefined;

      if (!row) {
        return {
          isValid: false,
          error: `SKU '${proposed.sku}' does not exist or is inactive in merchant catalog`,
          resolvedItems: [],
          totalAmount: 0,
          totalTax: 0,
          categories: [],
        };
      }

      const item: CatalogItem = {
        sku: String(row.sku),
        name: String(row.name),
        category: String(row.category),
        unit_price: Number(row.unit_price),
        tax_rate_bps: Number(row.tax_rate_bps),
        available_stock: Number(row.available_stock),
        is_active: Boolean(row.is_active),
      };

      if (item.available_stock < proposed.quantity) {
        return {
          isValid: false,
          error: `Insufficient stock for SKU '${proposed.sku}': requested ${proposed.quantity}, available ${item.available_stock}`,
          resolvedItems: [],
          totalAmount: 0,
          totalTax: 0,
          categories: [],
        };
      }

      const subtotal = item.unit_price * proposed.quantity;
      const tax = Math.round((subtotal * item.tax_rate_bps) / 10000);
      const total = subtotal + tax;

      grandTotal += total;
      grandTax += tax;
      categoriesSet.add(item.category);

      resolved.push({
        item,
        quantity: proposed.quantity,
        subtotal,
        tax,
        total,
      });
    }

    return {
      isValid: true,
      resolvedItems: resolved,
      totalAmount: grandTotal,
      totalTax: grandTax,
      categories: Array.from(categoriesSet),
    };
  }
}
